version: "3"
services: 
    registry:
        environment:
            REGISTRY_AUTH: htpasswd
            REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
            REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
            REGISTRY_STORAGE: s3
            REGISTRY_STORAGE_CACHE_BLOBDESCRIPTOR: inmemory
            REGISTRY_STORAGE_DELETE_ENABLED: "true"
            REGISTRY_STORAGE_S3_ACCESSKEY: <AWS Access Key>
            REGISTRY_STORAGE_S3_BUCKET: <AWS S3 bucket nmae>
            REGISTRY_STORAGE_S3_REGION: <AWS Region>
            REGISTRY_STORAGE_S3_SECRETKEY: <AWS Secret Key>
        image: registry:2
        restart: always
        ports:
            - 9099:5000
        volumes:
            - ./auth:/auth
        container_name: registry


