version: "3"
services: 
    registry:
        env_file: 
            - ./registry.env
        image: registry:2
        restart: always
        ports:
            - 9099:5000
        volumes:
            - ./auth:/auth
        container_name: registry


